package mypack;

// File Name SendEmail.java

import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;

public class SendEmail1
{
   public static void setmail(String name,String sname,String phone,String email,int grand)
   {
		// Recipient's email ID needs to be mentioned.
		String to = email;

		// Sender's email ID needs to be mentioned
		String from = "theonlinegroceryshop@gmail.com";

		// Assuming you are sending email from localhost
		  

		// Get system properties
		Properties properties = System.getProperties();

		// Setup mail server
		//properties.setProperty("mail.smtp.host", host);
		properties.setProperty("mail.smtp.host", "smtp.gmail.com");
		properties.setProperty("mail.smtp.auth", "true");
		properties.setProperty("mail.smtp.port","587");
		properties.setProperty("mail.smtp.starttls.enable", "true");
	 

		// Get the default Session object.
		Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication("theonlinegroceryshop@gmail.com", "groceryshop");
			}
		});

		try{
			// Create a default MimeMessage object.
			MimeMessage message = new MimeMessage(session);

			// Set From: header field of the header.
			message.setFrom(new InternetAddress(from));

			// Set To: header field of the header.
			message.addRecipient(Message.RecipientType.TO,
									  new InternetAddress(to));

			// Set Subject: header field
			message.setSubject("Online Grocery Shop: Order Accepted Successfully Please donot reply");

			// Now set the actual message
			message.setText("Dear "+name+" "+sname+" \nYour order has been processed. Your bill amount is Rs "+grand+" \n We will try to deliver your package within 24 hours. Please keep your mobile switched on whose number is "+phone+"\n\n Thankyou for Shopping with us\n\n\n Regards: \n The Online Grocery Shop\n\n\n This is an Autogenerated Email please donot reply.");

			// Send message
			Transport.send(message);
			System.out.println("Sent message successfully....");
                        
		}catch (MessagingException mex) {
			mex.printStackTrace();
		}
	}
}